sudo: required
services:
  - docker

before_install:
  - docker build -t jorgeyza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jorgeyza/react-test npm run test

after_success:
  - docker build -t jorgeyza/multi-client ./client
  - docker build -t jorgeyza/multi-nginx ./nginx
  - docker build -t jorgeyza/multi-server ./server
  - docker build -t jorgeyza/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to Docker Hub
  - docker push jorgeyza/multi-client
  - docker push jorgeyza/multi-nginx
  - docker push jorgeyza/multi-server
  - docker push jorgeyza/multi-worker